### ISSUE TITLE
Persist and restore AtmosphericPSFs screens in the checkpoint

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#117]
To use the atmospheric screens correctly when restarting a checkpointed imSim run, I think we need to persist the screens once they are created and read them in again when restarting from a checkpoint.

@jmeyers314 Do you have any recommendations for the best way to persist the `AtmosphericPSF` data?  I tried just pickling a psf object, but got `TypeError: can't pickle _thread.RLock objects`.  It seems that the `AtmosphericPSF.atm` and `AtmosphericPSF.aper` attributes are individually pickleable, so maybe that's the way to go, but we'd need a way to recreate an `AtmosphericPSF` object from its sub-components.

**Comment by jmeyers314** [comment]
Hi @jchiang87 ,  do you have an example script that can reproduce this error?  I wasn't initially able to get an AtmosphericPSF to pickle on my workstation, but I think that was just because I ran out of memory.  If I change line https://github.com/LSSTDESC/imSim/blob/master/python/desc/imsim/atmPSF.py#L142 to have `screen_size=102.4` instead of 819.2, though, then the following snippet runs just fine:

```python
import pickle
import galsim
from desc.imsim import AtmosphericPSF
atmPSF = AtmosphericPSF(airmass=1.2, rawSeeing=0.7, band='i', rng=galsim.BaseDeviate(123))

atmPSF2 = pickle.loads(pickle.dumps(atmPSF))

# Can only check the parts that have a meaningful __eq__, which doesn't include
# the final screen in atm at the moment...
assert atmPSF.atm[:-1] == atmPSF2.atm[:-1]
assert atmPSF.aper == atmPSF2.aper
```

**Comment by jchiang87** [comment]
Hi @jmeyers314, 
Using the `multiprocessing_treering_atm_merge` branch, I ran this:
```
import pickle
import desc.imsim

desc.imsim.read_config()

instcat = '/global/cscratch1/sd/descpho/Pipeline-tasks/DC2-R1-2p-WFD-i/000121/instCat/phosim_cat_261992.txt'

commands = desc.imsim.metadata_from_file(instcat)

obs_md = desc.imsim.phosim_obs_metadata(commands)

psf = desc.imsim.make_psf('Atmospheric', obs_md)

with open('atm_psf.pkl', 'wb') as output:
    pickle.dump(psf, output)
```
and got this:
```
[cori02] python test_atm_psf_persist.py
/global/cscratch1/sd/jchiang8/imsim_pipeline/imSim/python/desc/imsim/imSim.py:143: UserWarning:                                                                                     
Extra commands in the instance catalog /global/cscratch1/sd/descpho/Pipeline-tasks/DC2-R1-2p-WFD-i/000121/instCat/phosim_cat_261992.txt that are not in the required set:           
   camconfig                                                                              
   minsource                                                                              
  warnings.warn(message)                                                                  
Traceback (most recent call last):                                                        
  File "test_atm_psf_persist.py", line 15, in <module>                                    
    pickle.dump(psf, output)                                                              
TypeError: can't pickle _thread.RLock objects 
```
That `make_psf` function should just be returning a bare `AtmosphericPSF` object (and I've run that script successfully substituting the other PSFs, `DoubleGaussian`, `Kolmogorov`), so I'm really puzzled why your script works, but this one has that `_thread.RLock` attached.

**Comment by jmeyers314** [comment]
So I think I've narrowed this down to being a problem with pickling the logger.  I.e., it's this: https://bugs.python.org/issue30520.  I'm guessing the reason my snippet worked and @jchiang87 's didn't is because the logger was `None` in one case (pickles fine), and was an actual logger object in the other case (fails).

I don't know much about loggers, but I bet if we follow the commit on the python issue page linked above (apparently pickling loggers was added to py3.7), we could get this to work.

**Comment by jchiang87** [comment]
Thanks for looking into this Josh.  Since this is for checkpointing purposes, we can probably just workaround the logger by setting that attribute to `None` before pickling and then setting it back appropriately when it's unpickled.

**Comment by jmeyers314** [comment]
Sure, that sounds good.  Do you want to tackle this @jchiang87 , since you know how the checkpointing works?

One other possible thing to think about: There's some room to trade storage for speed if that matters (I'm not certain enough about the use case here to say).  Currently, pickling the atmosphere generates a pretty big pickle file (~6GB, though this may change if we ever decide on different # of layers, layer size, resolution, etc...)  If we just pickle the arguments used to construct the atmosphere though, it's probably no more than a few kb.  I'm sure it takes more time to do the reconstruction though than to read in the big pickle file.

**Comment by jchiang87** [comment]
Sure, I can deal with this.  In the current runs, we've been handling this by creating a separate rng object for the atmospheres and using the same seed on restart.  So we're sort of already trading off storage for speed.
