### ISSUE TITLE
We are double counting the noise during FFT drawing.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/imSim#419]
@matroxel noticed that in FFT drawing we use the realized flux and then add noise later. 

https://github.com/LSSTDESC/imSim/blob/main/imsim/stamp.py#L577
https://github.com/LSSTDESC/imSim/blob/main/imsim/stamp.py#L626

This seems like double counting the noise and it looks like line 577 should be

```
gal = gal.withFlux(self.flux, bandpass)
```

I think this might be a transcription error from when the code was being copied from the old system into the new GalSim config code base.  @rmjarvis can you confirm that's what happened and we should change this?

**Comment by matroxel** [comment]
You still need that line with realized_flux within the second if branch for the nonFFT version.

**Comment by rmjarvis** [comment]
Yes, Troxel and I already talked about it.  We should be using the non-Poisson flux for FFT drawing, since the addition of Poisson noise later does the job.

**Comment by rmjarvis** [comment]
Except the change you mentioned isn't correct.  Rather, we need to move that line as it stands to inside the phot branch.  And use the regular flux in the fft branch.

**Comment by rmjarvis** [comment]
Another thing we talked about is that in the Roman code, Troxel has been making decisions about when to switch to FFT based on the nominal flux, rather than the realized flux.  This is probably better, so a given object has the same behavior on all exposures, rather than possibly switching from phot to FFT (or in our case, real vs trivial SED) from one exposure to another. 

I think this makes more sense, so unless I get push back, let's do that in imSIm too.

**Comment by cwwalter** [comment]
@rmjarvis and @jchiang87 @matroxel Checking: did this happen in both code bases?

**Comment by rmjarvis** [comment]
Yes, I think so.

**Comment by cwwalter** [comment]
Thanks.  Closing.
