### ISSUE TITLE
Convert sersic2d position angles in the instance catalogs to radians

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#42]
The `sims_GalSimInterface` code expects radians for the position angle, but the units in the instance catalogs are degrees.

**Comment by danielsf** [comment]
The policy in `CatSim` is that, as soon as an angle is read in from the user, it is converted to radians and manipulated that way.  Angles are converted back to degrees (or arcseconds or milliarcseconds in the case of things like proper motion) before passing back to the user.  Since `ImSim` has taken things that were previously hidden from the user and exposed them, we might run into this problem elsewhere.  I tried to be careful about documenting the expected units of angles in the `CatSim` docstrings.  Let me know if anything is ambiguous.

**Comment by jchiang87** [comment]
Thanks, it's good to know about that policy for future reference.

**Comment by danielsf** [comment]
It just occurred to me that knowing this might be helpful:

Every time you see `CatSim` get an angle with `theta = self.column_by_name('theta')`, then `theta` is in radians (that is the practical implication of the policy I mentioned above).

**Comment by jchiang87** [comment]
It looks like the `transformations` class variable complicates that interpretation somewhat?

https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimCatalogs.py#L145

https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimCatalogs.py#L330

**Comment by danielsf** [comment]
The `transformations` dict is applied at the last possible moment before `write_catalog()` writes a catalog to disk.  This is so that, even though our code handles RA, Dec in radians, our users can still see them in degrees.  In theory, the transformations from degrees to radians and back again are supposed to be invisible to users.

**Comment by danielsf** [comment]
(`write_catalog()` is a method of the `InstanceCatalog` class)
