### ISSUE TITLE
Add capability to read in real phosim instance catalogs

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/imSim#51]
CatSim code would then be used to apply Earth precession and nutation to convert to geocentric apparent RA, Dec.   We should retain the ability to read in PhoSim compatible instance catalogs.

**Comment by danielsf** [comment]
Six months ago, I got it into my head that there should be methods in CatSim to undo the transformations between ICRS coordinates and what PhoSim expects (so that we could read in a PhoSim catalog and convert back to ICRS coordinates).  My attempt to do that uncovered some bugs in PALPY.  Those bugs have been fixed.  I will make another attempt.  Once that is done, we should be able to read in a PhoSim InstanceCatalog and run ImSim on it.

**Comment by cwwalter** [comment]
The key is undoing the transformations to the coordinates that phosim expects to ICRS, as Scott notes.

**Comment by cwwalter** [comment]
I think we are now doing this, correct @danielsf ?

**Comment by danielsf** [comment]
Yes.  This can be closed.
